export const GET_CONFIGURATIONS = "GET_CONFIGURATIONS";
export const GET_SELECTED_OFFER = "GET_SELECTED_OFFER";
export const SUBSCRIBE_TO_OFFER = "SUBSCRIBE_TO_OFFER";
export const GET_OFFER_IMAGE = "GET_OFFER_IMAGE";